name: Build and Test
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          architecture: x64
      - name: Display version
        run: python -c "import sys; print(sys.version)"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Run script.py
        run: python script.py
